export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED';
export const REGISTRATION_SUCCEEDED = 'REGISTRATION_SUCCEEDED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_AUTO_LOGOUT = 'AUTH_AUTO_LOGOUT';
export const AUTH_CHECK = 'AUTH_CHECK';

export const INCOME_GET_REQUESTED = 'INCOME_GET_REQUESTED';
export const INCOME_GET_SUCCEEDED = 'INCOME_GET_SUCCEEDED';

export const INCOME_DELETE_REQUESTED = 'INCOME_DELETE_REQUESTED';
export const INCOME_DELETE_SUCCEEDED = 'INCOME_DELETE_SUCCEEDED';
export const INCOME_DELETE_FAILED = 'INCOME_DELETE_FAILED';

export const INCOME_ADD_REQUESTED = 'INCOME_ADD_REQUESTED';
export const INCOME_ADD_SUCCEEDED = 'INCOME_ADD_SUCCEEDED';
export const INCOME_ADD_FAILED = 'INCOME_ADD_FAILED';

export const INCOME_EDIT_REQUESTED = 'INCOME_EDIT_REQUESTED';
export const INCOME_EDIT_SUCCEEDED = 'INCOME_EDIT_SUCCEEDED';
export const INCOME_EDIT_FAILED = 'INCOME_EDIT_FAILED';

export const INCOME_TYPE_DELETE_REQUESTED = 'INCOME_TYPE_DELETE_REQUESTED';
export const INCOME_TYPE_DELETE_SUCCEEDED = 'INCOME_TYPE_DELETE_SUCCEEDED';
export const INCOME_TYPE_DELETE_FAILED = 'INCOME_TYPE_DELETE_FAILED';

export const INCOME_TYPE_ADD_REQUESTED = 'INCOME_TYPE_ADD_REQUESTED';
export const INCOME_TYPE_ADD_SUCCEEDED = 'INCOME_TYPE_ADD_SUCCEEDED';
export const INCOME_TYPE_ADD_FAILED = 'INCOME_TYPE_ADD_FAILED';

export const INVESTMENT_GET_REQUESTED = 'INVESTMENT_GET_REQUESTED';
export const INVESTMENT_GET_SUCCEEDED = 'INVESTMENT_GET_SUCCEEDED';

export const INVESTMENT_DELETE_REQUESTED = 'INVESTMENT_DELETE_REQUESTED';
export const INVESTMENT_DELETE_SUCCEEDED = 'INVESTMENT_DELETE_SUCCEEDED';
export const INVESTMENT_DELETE_FAILED = 'INVESTMENT_DELETE_FAILED';

export const INVESTMENT_ADD_REQUESTED = 'INVESTMENT_ADD_REQUESTED';
export const INVESTMENT_ADD_SUCCEEDED = 'INVESTMENT_ADD_SUCCEEDED';
export const INVESTMENT_ADD_FAILED = 'INVESTMENT_ADD_FAILED';

export const INVESTMENT_EDIT_REQUESTED = 'INVESTMENT_EDIT_REQUESTED';
export const INVESTMENT_EDIT_SUCCEEDED = 'INVESTMENT_EDIT_SUCCEEDED';
export const INVESTMENT_EDIT_FAILED = 'INVESTMENT_EDIT_FAILED';

export const INVESTMENT_TYPE_DELETE_REQUESTED = 'INVESTMENT_TYPE_DELETE_REQUESTED';
export const INVESTMENT_TYPE_DELETE_SUCCEEDED = 'INVESTMENT_TYPE_DELETE_SUCCEEDED';
export const INVESTMENT_TYPE_DELETE_FAILED = 'INVESTMENT_TYPE_DELETE_FAILED';

export const INVESTMENT_TYPE_ADD_REQUESTED = 'INVESTMENT_TYPE_ADD_REQUESTED';
export const INVESTMENT_TYPE_ADD_SUCCEEDED = 'INVESTMENT_TYPE_ADD_SUCCEEDED';
export const INVESTMENT_TYPE_ADD_FAILED = 'INVESTMENT_TYPE_ADD_FAILED';

export const CURRENT_INVESTMENT_YEAR_CHANGE = 'CURRENT_INVESTMENT_YEAR_CHANGE';

export const INVESTMENT_GOALS_GET_REQUESTED = 'INVESTMENT_GOALS_GET_REQUESTED';
export const INVESTMENT_GOALS_GET_SUCCEEDED = 'INVESTMENT_GOALS_GET_SUCCEEDED';

export const INVESTMENT_GOAL_DELETE_REQUESTED = 'INVESTMENT_GOAL_DELETE_REQUESTED';
export const INVESTMENT_GOAL_DELETE_SUCCEEDED = 'INVESTMENT_GOAL_DELETE_SUCCEEDED';
export const INVESTMENT_GOAL_DELETE_FAILED = 'INVESTMENT_GOAL_DELETE_FAILED';

export const INVESTMENT_GOAL_ADD_REQUESTED = 'INVESTMENT_GOAL_ADD_REQUESTED';
export const INVESTMENT_GOAL_ADD_SUCCEEDED = 'INVESTMENT_GOAL_ADD_SUCCEEDED';
export const INVESTMENT_GOAL_ADD_FAILED = 'INVESTMENT_GOAL_ADD_FAILED';

export const INVESTMENT_GOAL_EDIT_REQUESTED = 'INVESTMENT_GOAL_EDIT_REQUESTED';
export const INVESTMENT_GOAL_EDIT_SUCCEEDED = 'INVESTMENT_GOAL_EDIT_SUCCEEDED';
export const INVESTMENT_GOAL_EDIT_FAILED = 'INVESTMENT_GOAL_EDIT_FAILED';

export const OVERVIEW_GET_REQUESTED = 'OVERVIEW_GET_REQUESTED';
export const OVERVIEW_GET_SUCCEEDED = 'OVERVIEW_GET_SUCCEEDED';

export const CHANGE_HEADER_TITLE = 'CHANGE_HEADER_TITLE';

export const RESET_GENERAL_ALERTS = 'RESET_GENERAL_ALERTS';
export const ADD_INFO_ALERT = 'ADD_INFO_ALERT';
export const ADD_ERROR_ALERT = 'ADD_ERROR_ALERT';

export const SET_ACTIVE_WALLET = 'SET_ACTIVE_WALLET';
export const ADD_WALLET_REQUESTED = 'ADD_WALLET_REQUESTED';
export const ADD_WALLET_SUCCEEDED = 'ADD_WALLET_SUCCEEDED';

export const EDIT_WALLET_REQUESTED = 'EDIT_WALLET_REQUESTED';
export const EDIT_WALLET_SUCCEEDED = 'EDIT_WALLET_SUCCEEDED';

export const DELETE_WALLET_REQUESTED = 'DELETE_WALLET_REQUESTED';
export const DELETE_WALLET_SUCCEEDED = 'DELETE_WALLET_SUCCEEDED';

export const SET_TRANSACTION_CATEGORIES = 'SET_TRANSACTION_CATEGORIES';

export const TRANSACTIONS_GET_REQUESTED = 'TRANSACTIONS_GET_REQUESTED';
export const TRANSACTIONS_GET_SUCCEEDED = 'TRANSACTIONS_GET_SUCCEEDED';

export const TRANSACTION_ADD_SUCCEEDED = 'TRANSACTION_ADD_SUCCEEDED';
