version: '3'
services:
  client:
    build: ./client
    volumes:
      - "./client:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - "./server:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'