version: "3"
services:
  server:
    build: ./server
    volumes:
      - "./server:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
