export const INCOME_GET_ALL_REQUESTED = "INCOME_GET_ALL_REQUESTED"
export const INCOME_GET_ALL_SUCCEEDED = "INCOME_GET_ALL_SUCCEEDED"
export const INIT_INCOME_DATA_FAILED = "INIT_INCOME_DATA_FAILED"

export const INCOME_DELETE_REQUESTED = "INCOME_DELETE_REQUESTED";
export const INCOME_DELETE_SUCCEEDED = "INCOME_DELETE_SUCCEEDED";
export const INCOME_DELETE_FAILED = "INCOME_DELETE_FAILED";

export const INCOME_ADD_REQUESTED = "INCOME_ADD_REQUESTED";
export const INCOME_ADD_SUCCEEDED = "INCOME_ADD_SUCCEEDED";
export const INCOME_ADD_FAILED = "INCOME_ADD_FAILED";

export const INCOME_EDIT_REQUESTED = "INCOME_EDIT_REQUESTED";
export const INCOME_EDIT_SUCCEEDED = "INCOME_EDIT_SUCCEEDED";
export const INCOME_EDIT_FAILED = "INCOME_EDIT_FAILED";