export const AUTH_REQUESTED = "AUTH_REQUESTED";
export const AUTH_SUCCEEDED = "AUTH_SUCCEEDED";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_AUTO_LOGOUT = "AUTH_AUTO_LOGOUT ";
export const AUTH_CHECK = "AUTH_CHECK";

export const INCOME_GET_ALL_REQUESTED = "INCOME_GET_ALL_REQUESTED"
export const INCOME_GET_ALL_SUCCEEDED = "INCOME_GET_ALL_SUCCEEDED"

export const INCOME_DELETE_REQUESTED = "INCOME_DELETE_REQUESTED";
export const INCOME_DELETE_SUCCEEDED = "INCOME_DELETE_SUCCEEDED";
export const INCOME_DELETE_FAILED = "INCOME_DELETE_FAILED";

export const INCOME_ADD_REQUESTED = "INCOME_ADD_REQUESTED";
export const INCOME_ADD_SUCCEEDED = "INCOME_ADD_SUCCEEDED";
export const INCOME_ADD_FAILED = "INCOME_ADD_FAILED";

export const INCOME_EDIT_REQUESTED = "INCOME_EDIT_REQUESTED";
export const INCOME_EDIT_SUCCEEDED = "INCOME_EDIT_SUCCEEDED";
export const INCOME_EDIT_FAILED = "INCOME_EDIT_FAILED";

export const INCOME_TYPE_DELETE_REQUESTED = "INCOME_TYPE_DELETE_REQUESTED";
export const INCOME_TYPE_DELETE_SUCCEEDED = "INCOME_TYPE_DELETE_SUCCEEDED";
export const INCOME_TYPE_DELETE_FAILED = "INCOME_TYPE_DELETE_FAILED";

export const INCOME_TYPE_ADD_REQUESTED = "INCOME_TYPE_ADD_REQUESTED";
export const INCOME_TYPE_ADD_SUCCEEDED = "INCOME_TYPE_ADD_SUCCEEDED";
export const INCOME_TYPE_ADD_FAILED = "INCOME_TYPE_ADD_FAILED";

export const CURRENT_INCOME_YEAR_CHANGE = "CURRENT_INCOME_YEAR_CHANGE";